### ISSUE TITLE
Extension for conceptual dictionary

### ISSUE THREAD

**Issue by aazocar** [OCDO/asmo#12]
Most of the needed terminology is focused on the subclasses of:

-  `Physical Quantity`, 
- `Calculated property`, 
- `Input Parameter` or 
- `Output Parameter`

Here we collect the classes to be added. Hierarchy for the properties will be discussed at a later point. 

@srmnitc please add here

**Comment by aazocar** [comment]
- Related to DFT (VASP) jobs:

| Superclass | Label | Definition | Comment |
|------------|-------|------------|---------|
|Calculated Property| Total Energy |            |         |
|Calculated Property| Potential Energy |            |         |
|Calculated Property| Pressure |            |         |
|Calculated Property| Volume |            |         |

**Comment by aazocar** [comment]
- Related to DFT (VASP) jobs:

| Superclass | Label | Definition | Comment |
|------------|-------|------------|---------|
|Calculated property| Total Energy |            |         |
|Calculated property| Total Magnetic Moment |            |         |
|Physical Quantity| SimulationCellLength |            |   change to PQ      |
|Physical Quantity| Pressure |            |         |
|Physical Quantity| Volume |            |         |
|Output Parameter| Number of ionic steps |            |         |
|Input Parameter| Energy Cutoff |            |         |
|Input Parameter| KPoint Mesh |           |     |
|KPoint Mesh| KPoint Mesh |           |  Explicit k-point mesh |
|KPoint Mesh| KPoint Mesh |           |  Gamma-centered mesh |
|KPoint Mesh| KPoint Mesh |           |  Monkhorst-Pack mesh |

**Comment by aazocar** [comment]
- Related to MD (LAMMPS) jobs:

| Superclass | Label | Definition | Comment |
|------------|-------|------------|---------|
|Physical Property| Temperature |            |  Used as InputParameter currently       |
|Physical Property| Pressure |            |  Used as InputParameter currently       |
|Physical Property| Volume |            |  Used as ComputedProperty currently       |
|Physical Property/CP| Kinetic Energy|            |         |
|Physical Property/CP| Potential Energy|            |         |
|Physical Quantity| SimulationCellLength |            |   change to PQ      |
|Physical Property/CP| Total Energy |            |         |
|PhysicalQuantity| Time |            |    |
|Input Parameter| TimeStep |            |       |
|Time| Simulation Time |            |   |

**Comment by aazocar** [comment]
- Related to EOS jobs:

| Superclass | Label | Definition | Comment |
|------------|-------|------------|---------|
|Input Parameter| Volume range |            |         |
|CalculatedProperty/PQ| TotalEnergy |            |  currently labelled EquilibriumEnergy |
|CalculatedProperty| BulkModulus |            |  |
|PhysicalProperty| Volume |            |  currently labelled EquilibriumVolume |

also simulation cell lengths as before..

**Comment by srmnitc** [comment]
- Related to QuasiHarmonic jobs:

| Superclass | Label | Definition | Comment |
|------------|-------|------------|---------|
|CalculatedProperty| FreeEnergy |            |  currently labelled QuasiHarmonicFreeEnergy |
|PhysicalProperty| Temperature |            | currently labelled QuasiHarmonicTemperature |
|PhysicalProperty| Volume |            |  currently labelled QuasiHarmonicVolume |

also simulation cell lengths as before..

**Comment by srmnitc** [comment]
- Related to ThermodynamicIntegration jobs:

| Superclass | Label | Definition | Comment |
|------------|-------|------------|---------|
|CalculatedProperty| FreeEnergy |            |   |
|PhysicalProperty| Temperature |            |  |
|PhysicalProperty| Volume |            | currently labelled AtomicVolume since its vol/atom |

also simulation cell lengths as before..

**Comment by srmnitc** [comment]
Further considerations
-------------------------

For LAMMPS:

- [Discussion] A major category we are missing are thermostats/barostats. We should consider if we want to add somethings like `hasThermostat` -> `Langevin` etc, and same for Barostat. Or simply use InputParameter.
- [NoTermNeeded] Force Tolerance, Energy tolerance etc for minimization - should be instantiated as needed using InputParameter.
- [NoTermNeeded] Initial, final, and averaged temperature, pressure, energy - covered by above definitions, instance can be used and labelled as needed.
- [NoTermNeeded] Force norm - should be ideally a per-atom quantity; otherwise it would be averaged force, max force etc which could be covered by OutputParameter
- [Discussion] MinimizationAlgorithm -  Algo used in  minimization, eg: conjugate gradient, full list [here](https://docs.lammps.org/min_style.html)  

For VASP:

- [ToDo] Import remaining XC functionals from MDO

General:

- PBC

**Comment by srmnitc** [comment]
@Tara-Lakshmipathy @pkruzikova After going through the OpenBis data model, this is the proposed update to the ontology. There are still some points to be discussed. If you have any suggestions or comments, please feel free to add here!

**Comment by srmnitc** [comment]
MASS?

**Comment by Tara-Lakshmipathy** [comment]
Did we agree on a strategy for periodic boundaries?

**Comment by srmnitc** [comment]
An additional, `PeriodicBoundaryConditions` -> `PeriodicityinXdirection` , similarly for `Y` and `Z` will be added.

**Comment by aazocar** [comment]
Ok, this is the schematic for the new classes. I'll go ahead with the changes now.
![iuc17 - ASMO_extension](https://github.com/user-attachments/assets/6a0ae33c-6bfa-4629-aba5-a865858bda35)
